### PR TITLE
Portal Search Flow-Thru

### PR DESCRIPTION
**Pull request by MrMaksimize**
screenshot

### CODE REVIEW

**Comment by MrMaksimize** [comment]
Would love some feedback @andrell81 also @47ronin

**Comment by 47ronin** [comment]
@MrMaksimize I like it. Also, If you check the graphic into the repo it can be added to the [README.md](https://github.com/cityofsandiego/datasd/blob/master/README.md) into an intro/background section as a screenshot, i.e.:
`[Screenshot](screenshot.png?raw=true)`

**Comment by MrMaksimize** [comment]
@47ronin done!

**Comment by MrMaksimize** [comment]
Waiting for @andrell81 to approve - she's the masta of design :)  @andrell81 approve / merge when ready

**Comment by 47ronin** [comment]
Can someone take a stab at placing a paragraph of copy above the screenshot as a project introduction?

**Comment by MrMaksimize** [comment]
@47ronin i'm thinking that should be a separate PR.  This has been sitting too long -- wanna get it merged :)

**Pull request merged**
